soinc.lo: /Users/xiangzhi/workspace/zephir/soinc/ext/soinc.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangzhi/workspace/zephir/soinc/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangzhi/workspace/zephir/soinc/ext/soinc.c -o soinc.lo 
kernel/main.lo: /Users/xiangzhi/workspace/zephir/soinc/ext/kernel/main.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangzhi/workspace/zephir/soinc/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangzhi/workspace/zephir/soinc/ext/kernel/main.c -o kernel/main.lo 
kernel/memory.lo: /Users/xiangzhi/workspace/zephir/soinc/ext/kernel/memory.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangzhi/workspace/zephir/soinc/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangzhi/workspace/zephir/soinc/ext/kernel/memory.c -o kernel/memory.lo 
kernel/exception.lo: /Users/xiangzhi/workspace/zephir/soinc/ext/kernel/exception.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangzhi/workspace/zephir/soinc/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangzhi/workspace/zephir/soinc/ext/kernel/exception.c -o kernel/exception.lo 
kernel/hash.lo: /Users/xiangzhi/workspace/zephir/soinc/ext/kernel/hash.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangzhi/workspace/zephir/soinc/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangzhi/workspace/zephir/soinc/ext/kernel/hash.c -o kernel/hash.lo 
kernel/debug.lo: /Users/xiangzhi/workspace/zephir/soinc/ext/kernel/debug.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangzhi/workspace/zephir/soinc/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangzhi/workspace/zephir/soinc/ext/kernel/debug.c -o kernel/debug.lo 
kernel/backtrace.lo: /Users/xiangzhi/workspace/zephir/soinc/ext/kernel/backtrace.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangzhi/workspace/zephir/soinc/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangzhi/workspace/zephir/soinc/ext/kernel/backtrace.c -o kernel/backtrace.lo 
kernel/object.lo: /Users/xiangzhi/workspace/zephir/soinc/ext/kernel/object.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangzhi/workspace/zephir/soinc/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangzhi/workspace/zephir/soinc/ext/kernel/object.c -o kernel/object.lo 
kernel/array.lo: /Users/xiangzhi/workspace/zephir/soinc/ext/kernel/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangzhi/workspace/zephir/soinc/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangzhi/workspace/zephir/soinc/ext/kernel/array.c -o kernel/array.lo 
kernel/extended/array.lo: /Users/xiangzhi/workspace/zephir/soinc/ext/kernel/extended/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangzhi/workspace/zephir/soinc/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangzhi/workspace/zephir/soinc/ext/kernel/extended/array.c -o kernel/extended/array.lo 
kernel/string.lo: /Users/xiangzhi/workspace/zephir/soinc/ext/kernel/string.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangzhi/workspace/zephir/soinc/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangzhi/workspace/zephir/soinc/ext/kernel/string.c -o kernel/string.lo 
kernel/fcall.lo: /Users/xiangzhi/workspace/zephir/soinc/ext/kernel/fcall.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangzhi/workspace/zephir/soinc/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangzhi/workspace/zephir/soinc/ext/kernel/fcall.c -o kernel/fcall.lo 
kernel/extended/fcall.lo: /Users/xiangzhi/workspace/zephir/soinc/ext/kernel/extended/fcall.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangzhi/workspace/zephir/soinc/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangzhi/workspace/zephir/soinc/ext/kernel/extended/fcall.c -o kernel/extended/fcall.lo 
kernel/require.lo: /Users/xiangzhi/workspace/zephir/soinc/ext/kernel/require.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangzhi/workspace/zephir/soinc/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangzhi/workspace/zephir/soinc/ext/kernel/require.c -o kernel/require.lo 
kernel/file.lo: /Users/xiangzhi/workspace/zephir/soinc/ext/kernel/file.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangzhi/workspace/zephir/soinc/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangzhi/workspace/zephir/soinc/ext/kernel/file.c -o kernel/file.lo 
kernel/operators.lo: /Users/xiangzhi/workspace/zephir/soinc/ext/kernel/operators.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangzhi/workspace/zephir/soinc/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangzhi/workspace/zephir/soinc/ext/kernel/operators.c -o kernel/operators.lo 
kernel/math.lo: /Users/xiangzhi/workspace/zephir/soinc/ext/kernel/math.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangzhi/workspace/zephir/soinc/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangzhi/workspace/zephir/soinc/ext/kernel/math.c -o kernel/math.lo 
kernel/concat.lo: /Users/xiangzhi/workspace/zephir/soinc/ext/kernel/concat.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangzhi/workspace/zephir/soinc/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangzhi/workspace/zephir/soinc/ext/kernel/concat.c -o kernel/concat.lo 
kernel/variables.lo: /Users/xiangzhi/workspace/zephir/soinc/ext/kernel/variables.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangzhi/workspace/zephir/soinc/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangzhi/workspace/zephir/soinc/ext/kernel/variables.c -o kernel/variables.lo 
kernel/filter.lo: /Users/xiangzhi/workspace/zephir/soinc/ext/kernel/filter.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangzhi/workspace/zephir/soinc/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangzhi/workspace/zephir/soinc/ext/kernel/filter.c -o kernel/filter.lo 
kernel/iterator.lo: /Users/xiangzhi/workspace/zephir/soinc/ext/kernel/iterator.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangzhi/workspace/zephir/soinc/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangzhi/workspace/zephir/soinc/ext/kernel/iterator.c -o kernel/iterator.lo 
kernel/time.lo: /Users/xiangzhi/workspace/zephir/soinc/ext/kernel/time.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangzhi/workspace/zephir/soinc/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangzhi/workspace/zephir/soinc/ext/kernel/time.c -o kernel/time.lo 
kernel/exit.lo: /Users/xiangzhi/workspace/zephir/soinc/ext/kernel/exit.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangzhi/workspace/zephir/soinc/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangzhi/workspace/zephir/soinc/ext/kernel/exit.c -o kernel/exit.lo 
soinc/exception.lo: /Users/xiangzhi/workspace/zephir/soinc/ext/soinc/exception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangzhi/workspace/zephir/soinc/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangzhi/workspace/zephir/soinc/ext/soinc/exception.zep.c -o soinc/exception.lo 
soinc/logger/processor/abstractprocessor.lo: /Users/xiangzhi/workspace/zephir/soinc/ext/soinc/logger/processor/abstractprocessor.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangzhi/workspace/zephir/soinc/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangzhi/workspace/zephir/soinc/ext/soinc/logger/processor/abstractprocessor.zep.c -o soinc/logger/processor/abstractprocessor.lo 
soinc/abstractmodule.lo: /Users/xiangzhi/workspace/zephir/soinc/ext/soinc/abstractmodule.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangzhi/workspace/zephir/soinc/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangzhi/workspace/zephir/soinc/ext/soinc/abstractmodule.zep.c -o soinc/abstractmodule.lo 
soinc/bootstrap.lo: /Users/xiangzhi/workspace/zephir/soinc/ext/soinc/bootstrap.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangzhi/workspace/zephir/soinc/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangzhi/workspace/zephir/soinc/ext/soinc/bootstrap.zep.c -o soinc/bootstrap.lo 
soinc/db/mysql.lo: /Users/xiangzhi/workspace/zephir/soinc/ext/soinc/db/mysql.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangzhi/workspace/zephir/soinc/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangzhi/workspace/zephir/soinc/ext/soinc/db/mysql.zep.c -o soinc/db/mysql.lo 
soinc/exception/db.lo: /Users/xiangzhi/workspace/zephir/soinc/ext/soinc/exception/db.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangzhi/workspace/zephir/soinc/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangzhi/workspace/zephir/soinc/ext/soinc/exception/db.zep.c -o soinc/exception/db.lo 
soinc/http/curl/extended.lo: /Users/xiangzhi/workspace/zephir/soinc/ext/soinc/http/curl/extended.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangzhi/workspace/zephir/soinc/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangzhi/workspace/zephir/soinc/ext/soinc/http/curl/extended.zep.c -o soinc/http/curl/extended.lo 
soinc/http/request/extended.lo: /Users/xiangzhi/workspace/zephir/soinc/ext/soinc/http/request/extended.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangzhi/workspace/zephir/soinc/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangzhi/workspace/zephir/soinc/ext/soinc/http/request/extended.zep.c -o soinc/http/request/extended.lo 
soinc/http/response/cookies.lo: /Users/xiangzhi/workspace/zephir/soinc/ext/soinc/http/response/cookies.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangzhi/workspace/zephir/soinc/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangzhi/workspace/zephir/soinc/ext/soinc/http/response/cookies.zep.c -o soinc/http/response/cookies.lo 
soinc/logger/adapter/file.lo: /Users/xiangzhi/workspace/zephir/soinc/ext/soinc/logger/adapter/file.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangzhi/workspace/zephir/soinc/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangzhi/workspace/zephir/soinc/ext/soinc/logger/adapter/file.zep.c -o soinc/logger/adapter/file.lo 
soinc/logger/formatter/line.lo: /Users/xiangzhi/workspace/zephir/soinc/ext/soinc/logger/formatter/line.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangzhi/workspace/zephir/soinc/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangzhi/workspace/zephir/soinc/ext/soinc/logger/formatter/line.zep.c -o soinc/logger/formatter/line.lo 
soinc/logger/processor/trace.lo: /Users/xiangzhi/workspace/zephir/soinc/ext/soinc/logger/processor/trace.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangzhi/workspace/zephir/soinc/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangzhi/workspace/zephir/soinc/ext/soinc/logger/processor/trace.zep.c -o soinc/logger/processor/trace.lo 
soinc/model/model.lo: /Users/xiangzhi/workspace/zephir/soinc/ext/soinc/model/model.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangzhi/workspace/zephir/soinc/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangzhi/workspace/zephir/soinc/ext/soinc/model/model.zep.c -o soinc/model/model.lo 
soinc/tools.lo: /Users/xiangzhi/workspace/zephir/soinc/ext/soinc/tools.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangzhi/workspace/zephir/soinc/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangzhi/workspace/zephir/soinc/ext/soinc/tools.zep.c -o soinc/tools.lo 
soinc/worker/taskabstract.lo: /Users/xiangzhi/workspace/zephir/soinc/ext/soinc/worker/taskabstract.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangzhi/workspace/zephir/soinc/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangzhi/workspace/zephir/soinc/ext/soinc/worker/taskabstract.zep.c -o soinc/worker/taskabstract.lo 
soinc/worker/worker.lo: /Users/xiangzhi/workspace/zephir/soinc/ext/soinc/worker/worker.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangzhi/workspace/zephir/soinc/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangzhi/workspace/zephir/soinc/ext/soinc/worker/worker.zep.c -o soinc/worker/worker.lo 
$(phplibdir)/soinc.la: ./soinc.la
	$(LIBTOOL) --mode=install cp ./soinc.la $(phplibdir)

./soinc.la: $(shared_objects_soinc) $(SOINC_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_soinc) $(SOINC_SHARED_LIBADD)

